### PR TITLE
Change ClassManifest for ClassTag (fixes #56), procedure syntax and clean up, Scala versions, disable failing test

### LINKED ISSUE #56: support 2.13

### PR DESCRIPTION
**Pull request by Sciss**
second commit

- changes all occurrences of deprecatd ClassManifest for ClassTag
- removes deprecated procedure syntax
- style: ensures all public methods are annotated with return types
  (except where it would break binary compatibility for 0.8; these
  should be fixed in 0.9)
- style: ensure implicit values are annotated with return types
  (pass values explictly where a statement would become recursive)
- style: remove unused identifiers (e.g. iteration variables that
  are not used)
- style: remove unnecessary parentheses
- use suggested improvements by IntelliJ: !isEmpty -> nonEmpty /
  isDefined etc.
- add mima plugin; verify that this commit is binary compatible with 0.8
- fix initialisation bug in `RetrySetBuilder` (`InitialCap` was zero)

first commit

- remove .idea -- this breaks IntelliJ on other computers
- update .gitignore accordingly
- clean up build.sbt, bump scala versions
- sbt version 1.1.1
- disable "multi-barrier deadlock cycle" test

### CODE REVIEW

File: src/main/scala/scala/concurrent/stm/ccstm/RetrySet.scala [hunk 1]
```diff
@@ -22,7 +22,7 @@ private[ccstm] class RetrySet(val size: Int,
     val d = begin + timeoutNanos
     val deadline = if (d < 0) Long.MaxValue else d // handle arithmetic overflow
 
-    val timeoutExceeded = !attemptAwait(deadline)
```
Comment (Sciss) [inline src/main/scala/scala/concurrent/stm/ccstm/RetrySet.scala]: I wonder if you were supposed to do anythinig with the result `timeoutExceeded`. Not using the value could point to a bug or to an unnecessary call to `attemptAwait`?

File: src/main/scala/scala/concurrent/stm/ccstm/Stats.scala [hunk 2]
```diff
@@ -25,7 +25,7 @@ private[ccstm] object Stats {
     def toStr(k: A): String = k.toString
 
     def contents: Seq[(String, Long)] = {
-      val aa = _counters.entrySet.toSeq map { e => (toStr(e.getKey) -> e.getValue.apply()) }
```
Comment (Sciss) [inline src/main/scala/scala/concurrent/stm/ccstm/Stats.scala]: This might be even improved performance-wise to `asScala.iterator.map(...).toSeq`?

File: src/main/scala/scala/concurrent/stm/japi/STM.scala [hunk 3]
```diff
@@ -53,7 +55,7 @@ object STM {
    * Create an empty TMap. Return a `java.util.Map` view of this TMap.
    * @return a new, empty `TMap.View` wrapped as a `java.util.Map`.
    */
-  def newMap[A, B](): JMap[A, B] = JavaConversions.mutableMapAsJavaMap(newTMap[A, B])
```
Comment (Sciss) [inline src/main/scala/scala/concurrent/stm/japi/STM.scala]: These should probably be changed to use `JavaConverters` instead; not sure what the equivalent code would be, so no changes here for now.

File: src/main/scala/scala/concurrent/stm/skel/TxnHashTrie.scala [hunk 4]
```diff
@@ -201,12 +202,12 @@ private[skel] object TxnHashTrie {
 
       // class manifests for classes that have type parameters are a bit
       // convoluted to construct, so it is better to do it only once per split
-      implicit val cm = implicitly[ClassManifest[Node[A, B]]]
```
Comment (Sciss) [inline src/main/scala/scala/concurrent/stm/skel/TxnHashTrie.scala]: This was a tricky line, because adding the value type creates an infinite loop (somehow it "works" without). Therefore, pass `cm` explicitly below.

File: src/test/scala/scala/concurrent/stm/IsolatedRefSuite.scala [hunk 5]
```diff
@@ -39,32 +41,32 @@ class IsolatedRefSuite extends FunSuite {
   // This implements Ref.View, but requires a surrounding InTxn context and
   // forwards to Ref's methods.
   class DynamicView[A](val ref: Ref[A]) extends Ref.View[A] {
-    implicit def txn = Txn.findCurrent.get
```
Comment (Sciss) [inline src/test/scala/scala/concurrent/stm/IsolatedRefSuite.scala]: Again, this "worked" only without type annotation; make sure we don't create infinite loop here.

File: src/test/scala/scala/concurrent/stm/TSetSuite.scala [hunk 6]
```diff
@@ -358,7 +358,6 @@ class TSetSuite extends FunSuite {
   test("view builder magic") {
     val s0 = TSet.View(1, 2, 3)
     val s1 = s0 map { "x" + _ }
-    val s2: TSet.View[String] = s1
```
Comment (Sciss) [inline src/test/scala/scala/concurrent/stm/TSetSuite.scala]: This is a no-op line which I removed. Perhaps you wanted to check that the type of `s1` was correct? Then I could add the line again, perhaps with a 'test' call so `s2` is referenced.

File: src/test/scala/scala/concurrent/stm/TMapSuite.scala [hunk 7]
```diff
@@ -398,13 +398,12 @@ class TMapSuite extends FunSuite {
 
   test("view builder magic") {
     val fwd = TMap.View(1 -> "one", 2 -> "two")
-    val rev = fwd map { kv => (kv._2 -> kv._1) }
-    val rev2: TMap.View[String, Int] = rev
```
Comment (Sciss) [inline src/test/scala/scala/concurrent/stm/TMapSuite.scala:402]: This is a no-op line. Perhaps you wanted to test the type inferred for `rev`. If so, I could re-add the line, perhaps calling a 'test' method so `rev2` is referenced.

File: src/test/scala/scala/concurrent/stm/examples/SyntaxCheatSheet.scala [hunk 8]
```diff
@@ -5,9 +5,9 @@ package scala.concurrent.stm.examples
 object SyntaxCheatSheet {
   import scala.concurrent.stm._
 
-  val x = Ref(0) // allocate a Ref[Int]
```
Comment (Sciss) [inline src/test/scala/scala/concurrent/stm/examples/SyntaxCheatSheet.scala:8]: Depending on the use case of the cheat sheet, perhaps we should not have explicit types here?

File: src/test/scala/scala/concurrent/stm/skel/SimpleRandomSuite.scala [hunk 9]
```diff
@@ -9,9 +9,8 @@ class SimpleRandomSuite extends FunSuite {
 
   test("nextInt") {
     val f = new SimpleRandom
-    val rand = new scala.util.Random
```
Comment (Sciss) [inline src/test/scala/scala/concurrent/stm/skel/SimpleRandomSuite.scala:12]: This value is never used
